### ISSUE TITLE
TrajectorySAPT Does Not Record All SAPT Energies

### ISSUE THREAD

**Issue by ALescoulie** [calpolyccg/MDSAPT#20]
SAPT breaks down non-covalent energy by type yet it is not recorded into our results. It should all be added to the results to give users more data since its already all calculated.

**Comment by armcdona** [comment]
This should definitely be a priority.

**Comment by ALescoulie** [comment]
I just need to find where in the docs it lists the key for those energies. I'd rather not have to read the output file manually

**Comment by armcdona** [comment]
I know this answer!  You use the psi4.variable function.  The answer is in hartrees so multiplying by 627.509 is to change to kcal/mole.

psi4.variable('SAPT ELST ENERGY') * 627.509
psi4.variable('SAPT EXCH ENERGY') * 627.509
psi4.variable('SAPT IND ENERGY') * 627.509
psi4.variable('SAPT DISP ENERGY') * 627.509
psi4.variable('SAPT TOTAL ENERGY') * 627.509

**Comment by ALescoulie** [comment]
Thanks that's one I can tick off, I already saved an instance variable for ht to kcal/mol
